# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "pip"  # Menentukan bahwa Anda menggunakan pip untuk manajemen paket
    directory: "/"  # Lokasi file requirements.txt, di sini diasumsikan berada di root
    schedule:
      interval: "weekly"  # Pembaruan dilakukan setiap minggu
    commit-message:
      prefix: "fix"  # Menambahkan awalan "fix" pada pesan commit pembaruan
      
# Konfigurasi untuk memperbarui GitHub Actions workflows
  - package-ecosystem: "github-actions"  # Menentukan pembaruan workflow GitHub Actions
    directory: "/.github/workflows/"  # Lokasi file workflows
    schedule:
      interval: "weekly"  # Pembaruan dilakukan setiap minggu
    commit-message:
      prefix: "chore"  # Menambahkan awalan "chore" pada pesan commit pembaruan
