name: Automate Absen

on:
  schedule:
    - cron: '0 9 * * *'  # Jalankan setiap hari pukul 09:00 UTC

jobs:
  automate-absen:
    runs-on: ubuntu-latest  # Server berbasis Linux

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Ambil kode dari repositori

    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable  # Instal Google Chrome

    - name: Install ChromeDriver
      run: |
        CHROME_VERSION=$(google-chrome --version | awk '{print $3}' | cut -d '.' -f 1)  # Ambil versi Chrome
        sudo apt-get install -y unzip
        wget -q "https://chromedriver.storage.googleapis.com/${CHROME_VERSION}.0/chromedriver_linux64.zip"
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/
        chmod +x /usr/local/bin/chromedriver

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Tentukan versi Python

    - name: Install dependencies
      run: |
        pip install -r requirements.txt  # Install pustaka Python seperti Selenium

    - name: Run Python script
      run: python script.py  # Jalankan file Python Anda
