name: Automate Absen (Docker)

on:
  schedule:
    - cron: '*/30 0-15 * * *'  # Jalankan setiap 30 menit dari jam 07:00-15:59 WIB
  workflow_dispatch:  # Jalan manual

jobs:
  automate-absen:
    runs-on: ubuntu-latest
    container:
      image: python:3.11-slim  # Gunakan Python container

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Ambil kode dari repo

    - name: Install Docker
      run: |
        apt-get install -y docker.io

    - name: Build Docker Image
      run: docker build -t absen-bot .

    - name: Run Docker Container
      run: docker run --rm --name absen-bot absen-bot

    - name: Upload screenshots
      uses: actions/upload-artifact@v4
      with:
        name: screenshots
        path: screenshots/
