name: Automate Absen

on:
  schedule:
    - cron: '10 * * * *'  # Jalankan setiap jam (0 pada setiap jam)
  workflow_dispatch:  # Opsi untuk menjalankan secara manual dari GitHub UI
jobs:
  automate-absen:
    runs-on: ubuntu-latest  # Server berbasis Linux

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Ambil kode dari repositori

    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable  

    - name: Install ChromeDriver
      run: |
        wget -N "https://storage.googleapis.com/chrome-for-testing-public/131.0.6778.108/linux64/chromedriver-linux64.zip" -P /tmp/
        sudo apt-get install -y unzip
        unzip /tmp/chromedriver-linux64.zip -d /tmp/
        sudo mv /tmp/chromedriver-linux64/chromedriver /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver
        rm -rf /tmp/chromedriver-linux64.zip /tmp/chromedriver-linux64

    - name: Verify Installations
      run: |
        google-chrome --version
        chromedriver --version

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Tentukan versi Python

    - name: Install dependencies
      run: |
        pip install -r requirements.txt  # Install pustaka Python seperti Selenium

    - name: Run Python script
      run: python Absen.py  # Jalankan file Python Anda
