name: Automate Absen

on:
  schedule:
    - cron: '*/30 0-15 * * *' #otomatis
  workflow_dispatch:  # Jalan manual
jobs:
  automate-absen:
    runs-on: ubuntu-latest  # akses pakai server linux
    
    env:
      PGHOST: ${{ vars.NEON_HOST }}
      PGDATABASE: ${{ vars.NEON_DB }}
      PGUSER: ${{ vars.NEON_USER }}
      PGPASSWORD: ${{ vars.NEON_PASSWORD }}
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # install repo

    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable  

    - name: Install Chrome for Testing (manual)
      run: |
        wget https://storage.googleapis.com/chrome-for-testing-public/136.0.7103.92/linux64/chrome-linux64.zip
        unzip chrome-linux64.zip
        sudo mv chrome-linux64 /opt/chrome
        sudo ln -s /opt/chrome/chrome /usr/bin/google-chrome
        google-chrome --version


    - name: Verify Installations
      run: |
        google-chrome --version
        chromedriver --version

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'  # versi python

    - name: Install dependencies
      run: |
        pip install -r requirements.txt  # Install pustaka Python seperti Selenium
        
    - name: Create screenshots directory
      run: mkdir -p screenshots
    
    - name: Run Python script
      run: python Absen.py  # run file py
      
    - name: Upload screenshots
      uses: actions/upload-artifact@v4
      with:
        name: screenshots
        path: screenshots/
