name: Automate Absen

on:
  workflow_dispatch:  # Jalan manual
jobs:
  automate-absen:
    runs-on: ubuntu-latest  # akses pakai server linux
    
    env:
      PGHOST: ${{ vars.NEON_HOST }}
      PGDATABASE: ${{ vars.NEON_DB }}
      PGUSER: ${{ vars.NEON_USER }}
      PGPASSWORD: ${{ vars.NEON_PASSWORD }}
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v5  # install repo

    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable  

    - name: Install ChromeDriver
      run: |
        wget -N "https://storage.googleapis.com/chrome-for-testing-public/139.0.7258.68/linux64/chromedriver-linux64.zip" -P /tmp/
        sudo apt-get install -y unzip
        unzip /tmp/chromedriver-linux64.zip -d /tmp/
        sudo mv /tmp/chromedriver-linux64/chromedriver /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver
        rm -rf /tmp/chromedriver-linux64.zip /tmp/chromedriver-linux64

    - name: Verify Installations
      run: |
        google-chrome --version
        chromedriver --version

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'  # versi python

    - name: Install dependencies
      run: |
        pip install -r requirements.txt  # Install pustaka Python seperti Selenium

    - name: Run Selenium script with xvfb
      run: |
        xvfb-run -a python script.py
        
    - name: Create screenshots directory
      run: mkdir -p screenshots
    
    - name: Run Python script
      run: python Absen.py  # run file py
      
    - name: Upload screenshots
      uses: actions/upload-artifact@v4
      with:
        name: screenshots
        path: screenshots/
