name: Automate Absen

on:
  schedule:
    - cron: '*/30 0-15 * * *' #otomatis
  workflow_dispatch:  # Jalan manual
jobs:
  automate-absen:
    runs-on: ubuntu-latest  # akses pakai server linux
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # install repo

    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable  

    - name: Install ChromeDriver
      run: |
        wget -N "https://storage.googleapis.com/chrome-for-testing-public/134.0.6998.88/linux64/chromedriver-linux64.zip" -P /tmp/
        sudo apt-get install -y unzip
        unzip /tmp/chromedriver-linux64.zip -d /tmp/
        sudo mv /tmp/chromedriver-linux64/chromedriver /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver
        rm -rf /tmp/chromedriver-linux64.zip /tmp/chromedriver-linux64

    - name: Verify Installations
      run: |
        google-chrome --version
        chromedriver --version

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'  # versi python

    - name: Install dependencies
      run: |
        pip install -r requirements.txt  # Install pustaka Python seperti Selenium
        
    - name: Create screenshots directory
      run: mkdir -p screenshots
    
    - name: Run Python script
      env:
        NEON_DB: neondb
        NEON_USER: neondb_owner
        NEON_PASSWORD: npg_wou3zV9hQSqM
        NEON_HOST: ep-divine-haze-a1db3adx-pooler.ap-southeast-1.aws.neon.tech'
      run: python Absen.py  # run file py
      
    - name: Upload screenshots
      uses: actions/upload-artifact@v4
      with:
        name: screenshots
        path: screenshots/
